/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bryan
 */
public class jfrmCalc extends javax.swing.JFrame {
    private String entrada = "";
    private int numero1, numero2;
    private String operador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalc.class.getName());

    /**
     * Creates new form jfrmCalc
     */
    public jfrmCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setText("0.0");
        jtxtCantidad.setEnabled(false);
        jtxtCantidad.addActionListener(this::jtxtCantidadActionPerformed);

        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(this::jbtnNum7ActionPerformed);

        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(this::jbtnNum8ActionPerformed);

        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(this::jbtnNum9ActionPerformed);

        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(this::jbtnNum4ActionPerformed);

        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(this::jbtnNum5ActionPerformed);

        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(this::jbtnNum6ActionPerformed);

        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(this::jbtnNum1ActionPerformed);

        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(this::jbtnNum2ActionPerformed);

        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(this::jbtnNum3ActionPerformed);

        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(this::jbtnNum0ActionPerformed);

        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(this::jbtnSumaActionPerformed);

        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(this::jbtnIgualActionPerformed);

        jbtnBorrar.setText("AC");
        jbtnBorrar.addActionListener(this::jbtnBorrarActionPerformed);

        jbtnResta.setText("-");
        jbtnResta.addActionListener(this::jbtnRestaActionPerformed);

        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(this::jbtnDiviActionPerformed);

        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);

        jbtnRaiz.setText("√");
        jbtnRaiz.addActionListener(this::jbtnRaizActionPerformed);

        jbtnC.setText("C");
        jbtnC.addActionListener(this::jbtnCActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnNum7)
                            .addComponent(jbtnNum4)
                            .addComponent(jbtnNum1)
                            .addComponent(jbtnNum0))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnNum2)
                            .addComponent(jbtnNum8)
                            .addComponent(jbtnNum5)
                            .addComponent(jbtnSuma))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnIgual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnMulti))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnNum9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnBorrar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnNum3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnDivi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnNum6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnResta)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnRaiz))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum7)
                    .addComponent(jbtnNum8)
                    .addComponent(jbtnNum9)
                    .addComponent(jbtnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum4)
                    .addComponent(jbtnNum5)
                    .addComponent(jbtnNum6)
                    .addComponent(jbtnResta)
                    .addComponent(jbtnRaiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum1)
                    .addComponent(jbtnNum2)
                    .addComponent(jbtnNum3)
                    .addComponent(jbtnDivi)
                    .addComponent(jbtnC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum0)
                    .addComponent(jbtnSuma)
                    .addComponent(jbtnIgual)
                    .addComponent(jbtnMulti))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "7";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "8";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "9";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "4";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "5";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "6";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "1";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "2";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "3";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "0";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        // TODO add your handling code here:
        numero1 = Integer.parseInt(entrada);
entrada = "";
operador = "+";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnSumaActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        // TODO add your handling code here:
        numero1 = Integer.parseInt(entrada);
entrada = "";
operador = "-";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        numero1 = Integer.parseInt(entrada);
entrada = "";
operador = "*";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        // TODO add your handling code here:
        numero1 = Integer.parseInt(entrada);
entrada = "";
operador = "/";
jtxtCantidad.setText("" + entrada);
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        // TODO add your handling code here:
        double resultado;
numero2 = Integer.parseInt(entrada);
jtxtCantidad.setText("");
entrada = "";

if (operador.equals("*")) {
    resultado = numero1 * numero2;
    entrada = String.valueOf(resultado);
    jtxtCantidad.setText("" + entrada);
} else if (operador.equals("+")) {
    resultado = numero1 + numero2;
    entrada = String.valueOf(resultado);
    jtxtCantidad.setText("" + entrada);
} else if (operador.equals("-")) {
    resultado = numero1 - numero2;
    entrada = String.valueOf(resultado);
    jtxtCantidad.setText("" + entrada);
} else if (operador.equals("/")) {
    resultado = numero1 / numero2;
    entrada = String.valueOf(resultado);
    jtxtCantidad.setText("" + entrada);
}
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        // TODO add your handling code here:
        entrada = "0";
jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(jtxtCantidad.getText());

if (valor >= 0) {
    valor = Math.sqrt(valor);
    jtxtCantidad.setText(String.valueOf(valor));
} else {
    jtxtCantidad.setText("Error");
}
    }//GEN-LAST:event_jbtnRaizActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
        String texto = jbtnC.getText();

if (texto.length() > 1) {
    texto = texto.substring(0, texto.length() - 1);
    jbtnC.setText(texto);
} else {
    jbtnC.setText("0");
}

    }//GEN-LAST:event_jbtnCActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
